-- 코드를 입력하세요
SELECT B.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(SALES * PRICE) AS TOTAL_SALES
FROM BOOK B, AUTHOR A, BOOK_SALES S
WHERE SALES_DATE LIKE '2022-01-%' AND B.AUTHOR_ID = A.AUTHOR_ID AND B.BOOK_ID = S.BOOK_ID
GROUP BY B.AUTHOR_ID, CATEGORY
ORDER BY B.AUTHOR_ID ASC, CATEGORY DESC

