-- 코드를 입력하세요
SELECT USERS.USER_ID, USERS.NICKNAME, SUM(BOARD.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD BOARD
JOIN USED_GOODS_USER USERS
ON BOARD.WRITER_ID = USERS.USER_ID
WHERE STATUS LIKE '%DONE%'
GROUP BY USERS.USER_ID HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES